const list=[
    {id:'1',nom:'ONUCI',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image: './IMAGE/onuci.png',categorie:"Aide à l'enfance"},
    {id:'2',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'3',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'4',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'5',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'6',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'7',nom:'ONUCI',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image: './IMAGE/onuci.png'},
    {id:'8',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'9',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'10',nom:'ONUCI',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image: './IMAGE/onuci.png'},
    {id:'11',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'12',categorie:"Aide à l'enfance",nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'13',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'14',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'15',nom:'ONUCI',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image: './IMAGE/onuci.png'},
    {id:'16',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'17',nom:'ONUCI',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image: './IMAGE/onuci.png'},
    {id:'18',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'19',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'20',nom:'Save the children',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/save.png'},
    {id:'21',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'},
    {id:'22',nom:'ONUCI',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image: './IMAGE/onuci.png'},
    {id:'23',nom:'Children of africa',description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos labore ut at excepturi. Esse, vero quibusdam sit numquam laboriosam necessitatibus modi repellat libero perspiciatis rem nobis maiores atque eveniet voluptatum.',image:'./IMAGE/child.png'}]
const infodon = {vue:100, ong:200,don:10}
const cartedescriptive=[
    {titre:'Un Don pour un Monde Meilleur',text:"En ce moment précis, vous pouvez être le héros dont une personne a besoin. Votre don, qu'il s'agisse d'une pièce de monnaie, d'un billet, d'un vêtement ou d'un produit alimentaire, peut ouvrir un monde d'opportunités pour ceux qui luttent contre les coups de la vie. Soyez la lueur d'espoir pour ceux plongés dans l'obscurité de l'incertitude, de la faim et de la maladie. Agissez dès aujourd'hui pour devenir le héros d'une personne.",image:'./IMAGE/fond5.jpg',infobouton:'Devenez un héros'},
    {titre:'Rejoignez-Nous',text:"Rejoignez Saraka et ensemble, faisons la différence en apportant un changement positif dans la vie des personnes qui en ont besoin. Chacun de nous a le pouvoir de contribuer à un monde meilleur. Rejoignez-nous aujourd'hui pour être le changement que vous souhaitez voir dans le monde.",image:'./IMAGE/Rejoignez.jpg',infobouton:'Rejoignez-Nous'}
]
export {list,infodon,cartedescriptive}